"""麦凯66客户档案字段。

公开资料中的 Mackay 66 Customer Profile 常见版本会按客户个人、家庭、公司、
兴趣、关系、业务往来等维度采集信息。这里结合美容养生门店做本地化字段。
"""

MEKAI66_FIELDS = [
    {"key": "name", "label": "姓名", "category": "基础信息"},
    {"key": "nickname", "label": "昵称/常用称呼", "category": "基础信息"},
    {"key": "gender", "label": "性别", "category": "基础信息"},
    {"key": "birthday", "label": "生日", "category": "基础信息"},
    {"key": "age", "label": "年龄", "category": "基础信息"},
    {"key": "hometown", "label": "籍贯/老家", "category": "基础信息"},
    {"key": "address", "label": "居住地址/小区", "category": "基础信息"},
    {"key": "phone", "label": "手机号", "category": "基础信息"},
    {"key": "wechat", "label": "微信号", "category": "基础信息"},
    {"key": "education", "label": "学历", "category": "基础信息"},
    {"key": "marital_status", "label": "婚姻状态", "category": "家庭关系"},
    {"key": "spouse_name", "label": "配偶姓名", "category": "家庭关系"},
    {"key": "spouse_job", "label": "配偶职业", "category": "家庭关系"},
    {"key": "children", "label": "子女情况", "category": "家庭关系"},
    {"key": "children_school", "label": "子女学校/年级", "category": "家庭关系"},
    {"key": "parents", "label": "父母情况", "category": "家庭关系"},
    {"key": "family_anniversary", "label": "家庭纪念日", "category": "家庭关系"},
    {"key": "family_focus", "label": "家庭关注点", "category": "家庭关系"},
    {"key": "pet", "label": "宠物", "category": "家庭关系"},
    {"key": "emergency_contact", "label": "紧急联系人", "category": "家庭关系"},
    {"key": "company", "label": "公司/单位", "category": "工作事业"},
    {"key": "industry", "label": "行业", "category": "工作事业"},
    {"key": "position", "label": "职位", "category": "工作事业"},
    {"key": "job_responsibility", "label": "工作职责", "category": "工作事业"},
    {"key": "income_level", "label": "收入水平", "category": "工作事业"},
    {"key": "work_pressure", "label": "工作压力", "category": "工作事业"},
    {"key": "work_schedule", "label": "作息/上下班时间", "category": "工作事业"},
    {"key": "business_needs", "label": "事业需求/目标", "category": "工作事业"},
    {"key": "decision_style", "label": "决策风格", "category": "工作事业"},
    {"key": "social_circle", "label": "社交圈", "category": "工作事业"},
    {"key": "hobbies", "label": "兴趣爱好", "category": "生活方式"},
    {"key": "sports", "label": "运动习惯", "category": "生活方式"},
    {"key": "travel", "label": "旅游偏好", "category": "生活方式"},
    {"key": "diet", "label": "饮食偏好", "category": "生活方式"},
    {"key": "tea_drink", "label": "茶饮偏好", "category": "生活方式"},
    {"key": "music", "label": "音乐偏好", "category": "生活方式"},
    {"key": "reading", "label": "阅读/学习偏好", "category": "生活方式"},
    {"key": "shopping", "label": "购物偏好", "category": "生活方式"},
    {"key": "brands", "label": "喜欢品牌", "category": "生活方式"},
    {"key": "taboo_topics", "label": "忌讳话题", "category": "生活方式"},
    {"key": "consumption_power", "label": "消费能力", "category": "消费习惯"},
    {"key": "consumption_frequency", "label": "消费频次", "category": "消费习惯"},
    {"key": "budget", "label": "预算区间", "category": "消费习惯"},
    {"key": "preferred_projects", "label": "偏好项目", "category": "消费习惯"},
    {"key": "disliked_projects", "label": "不喜欢项目", "category": "消费习惯"},
    {"key": "price_sensitivity", "label": "价格敏感度", "category": "消费习惯"},
    {"key": "promotion_preference", "label": "优惠偏好", "category": "消费习惯"},
    {"key": "referral_willingness", "label": "转介绍意愿", "category": "消费习惯"},
    {"key": "decision_factor", "label": "购买决策因素", "category": "消费习惯"},
    {"key": "loss_risk", "label": "流失风险点", "category": "消费习惯"},
    {"key": "skin_type", "label": "皮肤类型", "category": "健康美容"},
    {"key": "beauty_concerns", "label": "美容关注点", "category": "健康美容"},
    {"key": "body_discomfort", "label": "身体不适", "category": "健康美容"},
    {"key": "chronic_disease", "label": "慢性病/疾病史", "category": "健康美容"},
    {"key": "allergy", "label": "过敏史", "category": "健康美容"},
    {"key": "contraindication", "label": "护理禁忌", "category": "健康美容"},
    {"key": "sleep", "label": "睡眠情况", "category": "健康美容"},
    {"key": "menstruation", "label": "经期/备孕/孕产情况", "category": "健康美容"},
    {"key": "preferred_employee", "label": "偏好技师", "category": "服务偏好"},
    {"key": "service_strength", "label": "服务力度偏好", "category": "服务偏好"},
    {"key": "chat_preference", "label": "聊天偏好", "category": "服务偏好"},
    {"key": "room_preference", "label": "房间/环境偏好", "category": "服务偏好"},
    {"key": "temperature_preference", "label": "温度偏好", "category": "服务偏好"},
    {"key": "appointment_preference", "label": "预约时间偏好", "category": "服务偏好"},
    {"key": "last_important_event", "label": "最近重要事件", "category": "关系维护"},
    {"key": "next_followup", "label": "下次跟进重点", "category": "关系维护"},
]
